server:
  port: 8011
spring:
  application:
    name: eureka-server
management:
  security:
    enabled: true
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8012/eureka/