server:
  port: 8012
spring:
  application:
    name: eureka-server
management:
  security:
    enabled: true
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8011/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 6000