server:
  port: 8012
spring:
  application:
    name: eureka-server
management:
  security:
    enabled: true
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:8011/eureka/