server:
  port: 8022
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8012/eureka/
    fetch-registry: true
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  server:
    # 关闭Euraka的自我保护机制
    enable-self-preservation: false
spring:
  application:
    name: stoke-quote
management:
  security:
    enabled: false
